### ISSUE TITLE
Swift 3.1 Builds fail

### ISSUE THREAD

**Issue by benspratling4** [IBM-Bluemix/cf-deployment-tracker-client-swift#41]
This package depends on CloudConfiguration (IBM-Swift/CloudConfiguration) which needs v 2.0.0 to support Swift 3.1.
That package depends on CloudFoundryEnv (/IBM-Swift/Swift-cfenv), which needs v 4.0.0 to support Swift 3.1.
Builds currently fail for Kitura apps using CloudFoundry.  (But only on Linux)

**Comment by rolivieri** [comment]
@benspratling4 This library had not been migrated to Swift 3.1 at the time you encountered those problems. It is not migrated to Swift 3.1 and has been tagged 3.0.0.
